[package]
name = "rust-log-book"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.5.52", features = ["derive"] }
serde = "1.0.228"
